force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA{0}</displayFormat>
        <label>Event Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Attendee__c/Session_Attendee__c.object-meta.xml
<CustomObject>
    <label>Session Attendee</label>
    <nameField>
        <displayFormat>SA{0}</displayFormat>
        <label>Session Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Attendee__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Sessions Attendees</relationshipLabel>
    <relationshipName>Sessions_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionAttendeeHandler.cls
public class SessionAttendeeHandler {
    public static void sessionAttendees(List<Session_Attendee__c> saList, Map<Id,Session_Attendee__c>oldSessionAttendeesMap){
        set<Id> eaIds = new Set<Id>();
        for(Session_Attendee__c sa: saList){
            eaIds.add(sa.Event_Attendee__c);
        }
        List<Event_Attendee__c> eventAttd =[SELECT Id,Status__c FROM Event_Attendee__c WHERE Id IN: eaIds];
        for(Event_Attendee__c ea: eventAttd){
      List<Session_Attendee__c> relatedSessionAttd =[SELECT Id,Status__c FROM Session_Attendee__c WHERE Event_Attendee__c=:ea.Id];
            Boolean allAttd= true;
            for(Session_Attendee__c seAttd: relatedSessionAttd){
                if(seAttd.Status__c!='Attended'){
                    allAttd=false;
                    break;
                    
                }
            }
            if(allAttd){
                ea.Status__c='Attended';
            }
        }
        update eventAttd;
    }

}