force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/AccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>AccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountTransaction</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit Account</fullName>
            </value>
            <value>
                <fullName>Credit Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionTriggerHandler.cls
public class TransactionTriggerHandler {
    public static void paymentInsert(List<Transaction__c> transcList){
        // System.debug('HIIII'); 
        Set<Id> accIds = new Set<Id>();
        List<Account> accList=new List<Account>();
        for(Transaction__c t: transcList){
            // System.debug('Heloo');
            accIds.add(t.Id);
        }
        for(Transaction__c tr:[SELECT Id,Amount__c,Payment__c,AccountTransaction__c FROM Transaction__c WHERE Id IN:accIds ]){
            // System.debug('HEYYYY');
            if(tr.Payment__c=='Credit Account'){
                //  System.debug('HeYLOO');
                Account ac=new Account();
                ac.Id = tr.AccountTransaction__c;
                ac.TotalBalance__c= +tr.Amount__c;
                accList.add(ac);
                
            } else{
                
                // System.debug('BYYE');
                Account ac1=new Account();
                ac1.Id = tr.AccountTransaction__c;
                ac1.TotalBalance__c= -tr.Amount__c;
                accList.add(ac1);
            }
        }
        if(!accList.isEmpty()){
            // System.debug(accList);
            update accList;
            
        }
        
    }
    
}