force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA{0}</displayFormat>
        <label>Event Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events Attendees</relationshipLabel>
    <relationshipName>Events_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Session_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Attendee__c/Session_Attendee__c.object-meta.xml
<CustomObject>
    <label>Session Attendee</label>
    <nameField>
        <displayFormat>SA{0}</displayFormat>
        <label>Session Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Attendee__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Sessions Attendees</relationshipLabel>
    <relationshipName>Sessions_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Attendee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions Attendees</relationshipLabel>
    <relationshipName>Sessions_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventAttendeeHandler.cls
public class EventAttendeeHandler {
    public static void singleSessionEventAttendees(List<Event_Attendee__c> evtList) {
        List<Session_Attendee__c> sessionAttendees = new List<Session_Attendee__c>();

        Set<Id> eventIds = new Set<Id>();
        for (Event_Attendee__c attendee : evtList) {
            eventIds.add(attendee.Event__c);
        }

        Map<Id, Session__c> sessionMap = new Map<Id, Session__c>();
        for (Session__c session : [SELECT Id, Event__c FROM Session__c WHERE Event__c IN :eventIds]) {
            sessionMap.put(session.Event__c, session);
        }

        for (Event_Attendee__c attendee : evtList) {
            if (sessionMap.containsKey(attendee.Event__c)) {
                Session_Attendee__c sessionAttendee = new Session_Attendee__c();
                sessionAttendee.Event_Attendee__c = attendee.Id;
                sessionAttendee.Session__c = sessionMap.get(attendee.Event__c).Id;
                sessionAttendee.Email__c=attendee.Email__c;
                sessionAttendee.Status__c=attendee.Status__c;

                sessionAttendees.add(sessionAttendee);
            }
        }

        if (!sessionAttendees.isEmpty()) {
            insert sessionAttendees;
        }
    }
}