force-app/main/default/objects/Contact_Account_History__c/Contact_Account_History__c.object-meta.xml
<CustomObject>
    <label>Contact Account History</label>
    <nameField>
        <displayFormat>H-{00}</displayFormat>
        <label>Contact Account History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Accounts History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Account_History__c/fields/AccountsLookups__c.field-meta.xml
<CustomField>
    <fullName>AccountsLookups__c</fullName>
    <label>Account Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts Accounts History</relationshipLabel>
    <relationshipName>Contacts_Accounts_History</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Account_History__c/fields/ContactsLookup__c.field-meta.xml
<CustomField>
    <fullName>ContactsLookup__c</fullName>
    <label>Contact Lookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts Accounts History</relationshipLabel>
    <relationshipName>Contacts_Accounts_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContactHistoryHandler.cls
public class ContactHistoryHandler {
    public static void handleAfterInsert(List<Contact> newContacts) {
      //  System.debug('hii');
        List<Contact_Account_History__c> contactAccountHistories = new List<Contact_Account_History__c>();
       // System.debug('hiii');

       // System.debug('hello');

        for (Contact newContact : newContacts) {
          //  System.debug('hiiii');
            Contact_Account_History__c historyRecord = new Contact_Account_History__c();
              historyRecord.ContactsLookup__c = newContact.Id;
              historyRecord.AccountsLookups__c = newContact.AccountId;
              historyRecord.Designation__c = newContact.Designation__c;
            

            contactAccountHistories.add(historyRecord);
        }

       // System.debug(contactAccountHistories);

        if (!contactAccountHistories.isEmpty()) {
           insert contactAccountHistories;
        }
    }
}